"""Update embedding dimension to 256 for model2vec

Revision ID: 71868d3126af
Revises: 001
Create Date: 2025-08-02 15:35:34.493527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = '71868d3126af'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('meeting_chunks', 'embedding',
               existing_type=Vector(1536),
               type_=Vector(256),
               existing_nullable=True)
    op.drop_index(op.f('meeting_chunks_embedding_idx'), table_name='meeting_chunks', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='ivfflat')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('meeting_chunks_embedding_idx'), 'meeting_chunks', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='ivfflat')
    op.alter_column('meeting_chunks', 'embedding',
               existing_type=Vector(256),
               type_=Vector(1536),
               existing_nullable=True)
    # ### end Alembic commands ###