"""Add agenda_timestamps column to meetings table

Revision ID: b45fdfc43126
Revises: 71868d3126af
Create Date: 2025-08-02 18:23:12.399339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b45fdfc43126'
down_revision: Union[str, None] = '71868d3126af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meetings', sa.Column('agenda_timestamps', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meetings', 'agenda_timestamps')
    # ### end Alembic commands ###